G0: 64
RDNconfig: 'B'
RDNkSize: 3
act: 'relu'
batch_size: 16
# 命令行解析可以指定类型，yml也要注意
# betas: (0.9 0.999)    解析为字符串
betas: !!python/tuple [0.9,0.999]
chop: False
cpu: False
data_range: '1-800/801-810'
data_test: ['video']
data_train: ['DIV2K']
debug: False
decay: '200'
dilation: False
dir_data: '../../../dataset'
dir_demo: 'm.mp4'
epochs: 300
#  科学计数法默认是读成字符串
epsilon: !!float 1e-08
ext: 'sep'
extend: '.'
gamma: 0.5
gan_k: 1
gclip: 0
load: ''
loss: '1*L1'
lr: 0.0001
model: 'EDSR'
momentum: 0.9
n_GPUs: 1
n_colors: 3
n_feats: 64
n_resblocks: 16
n_resgroups: 10
n_threads: 6
no_augment: False
optimizer: 'ADAM'
patch_size: 192
pre_train: 'download'
precision: 'single'
print_every: 100
reduction: 16
res_scale: 1
reset: False 
resume: 0
rgb_range: 255
save: 'test'
save_gt: False
save_models: False
save_results: False
scale: [4]
seed: 1
self_ensemble: False
shift_mean: True
skip_threshold: 100000000.0
split_batch: 1
template: '.'
test_every: 1000
test_only: False
weight_decay: 0